# Generated by Django 4.1.7 on 2023-02-24 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_posts_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
