# Generated by Django 4.1.7 on 2023-02-27 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_posts_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
